# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  strategies:
    strategy:
      matrix:
        strategy: [ "github" ]
    uses: ./.github/workflows/test-workflow.yml
    with:
      workdir: strategies/${{ matrix.strategy }}

  omniauth:
    needs: strategies
    uses: ./.github/workflows/test-workflow.yml
    with:
      workdir: .